POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Jonas",
    "email": "joninha@gmail.com",
    "password": "fjdiosgjvnji"
}
###
GET http://localhost:3003/users
###
POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "Bulbasaur",
    "price": "2",
    "image_url": "https://cdn.goodvinilos.com/4608/pokemon-charmander.jpg"
}
###
GET http://localhost:3003/products
###
POST http://localhost:3003/purchases
Content-Type: application/json

{
    "user_id": "1662128697144",
    "product_id": "1662338382224",
    "quantity": 4
}
###
GET http://localhost:3003/users/1662128697144/purchases?order=desc&sort=quantity&search=charman