### Create user
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Shen",
    "email": "shen@gmail.com",
    "password": "nomoremasters"
}
### Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "shen@gmail.com",
    "password": "nomoremasters"
}
### Create post
POST http://localhost:3003/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwN2ZhNjViLWQyZjUtNGYxNi1hYjdiLTY3NWUzMjZmZTZmMiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjM5MzIxNzgsImV4cCI6MTY2MzkzNTc3OH0.ubuAA4GtcGNGqKztON0H_98cNGw81_oH1SBFlAx8ybY
Content-Type: application/json

{
    "content": "Shen Post"
}
### Get posts
GET http://localhost:3003/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQzMTNmOGExLThmNzQtNDE5ZC1iNjJmLWZlNGM1NjZkYWY2MCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjM5MzE1NjAsImV4cCI6MTY2MzkzNTE2MH0.NLQmTvdvBuJSR2djmKJoqZVT3CbEh3nypxYjM_pc8x8
### Delete post
DELETE http://localhost:3003/posts/96b1df92-8e14-4023-99d6-82dcc533dce4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQzMTNmOGExLThmNzQtNDE5ZC1iNjJmLWZlNGM1NjZkYWY2MCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MzkzMjIzMSwiZXhwIjoxNjYzOTM1ODMxfQ.NOn5PC5e_WhwJJQvlmopmBYWSU9kfa33g4nUzuzwxmY
### Like
POST http://localhost:3003/posts/like/7d259986-c33d-41de-acb9-79828d8b6114
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwN2ZhNjViLWQyZjUtNGYxNi1hYjdiLTY3NWUzMjZmZTZmMiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjM5MzYzNTUsImV4cCI6MTY2MzkzOTk1NX0.npjGgCRLayzP3xYDsb3cuUyVFhKYVrBOv_WgZqSpiAE
### Remove like
DELETE http://localhost:3003/posts/remove-like/7d259986-c33d-41de-acb9-79828d8b6114
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQzMTNmOGExLThmNzQtNDE5ZC1iNjJmLWZlNGM1NjZkYWY2MCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MzkzNTc3NSwiZXhwIjoxNjYzOTM5Mzc1fQ.110G8en_40MykOEmr32_u8dNbNBqiaT7JkXSNVCHx18