### Create user
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Shen",
    "email": "shen@gmail.com",
    "password": "equilibrio"
}
### Login user
POST http://localhost:3003/users/Login
Content-Type: application/json

{
    "email": "kali@gmail.com",
    "password": "nomoremasters"
}
### Create show
POST http://localhost:3003/shows/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAzYzZlOTBhLWZiZDgtNDhkNC05ODQ3LWQ2Zjk1NDY2ZDcwNiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NDU5MDIwMiwiZXhwIjoxNjY0NTkzODAyfQ.MAK9fpwEdzQAH8lTkwSHFBciS2zioCICwnzPbBYTA-4

{
    "band": "Bee Gees",
    "starts_at": "08/12/2022"
}
### Get shows
GET http://localhost:3003/shows
### Purchase ticket
POST http://localhost:3003/shows/purchase/b6e2b0e8-ccaf-40d3-819e-cfcacd1a33f3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAzYzZlOTBhLWZiZDgtNDhkNC05ODQ3LWQ2Zjk1NDY2ZDcwNiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NDY4NTY0MCwiZXhwIjoxNjY0Njg5MjQwfQ.wJId70q3z3PMOPXXTwfn4Py3tMPKoaZe6-XSclF3B9Q
### Deelete tickets
DELETE http://localhost:3003/shows/delete/dcb8bed0-b1cf-42f5-8f91-73bd4acdc042
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAzYzZlOTBhLWZiZDgtNDhkNC05ODQ3LWQ2Zjk1NDY2ZDcwNiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NDY0NTcxOCwiZXhwIjoxNjY0NjQ5MzE4fQ._nn6rQV_XteIp5-eJFHpXW0lhBiZjO70fohcTw6OyTU