### Create user
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Shen",
    "email": "shen@gmail.com",
    "password": "equilibrio"
}
### Login user
POST http://localhost:3003/users/Login
Content-Type: application/json

{
    "email": "shen@gmail.com",
    "password": "equilibrio"
}
### Create show
POST http://localhost:3003/shows/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAzYzZlOTBhLWZiZDgtNDhkNC05ODQ3LWQ2Zjk1NDY2ZDcwNiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NDU5MDIwMiwiZXhwIjoxNjY0NTkzODAyfQ.MAK9fpwEdzQAH8lTkwSHFBciS2zioCICwnzPbBYTA-4

{
    "band": "Bee Gees",
    "starts_at": "08/12/2022"
}
### Get shows
GET http://localhost:3003/shows
### Purchase ticket
POST http://localhost:3003/shows/purchase/b6e2b0e8-ccaf-40d3-819e-cfcacd1a33f3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhhZmMyNWI3LTgyMDEtNGM0OC1iYmYzLTFlZGQ4OWMyMTMxYyIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjQ1OTA0NTMsImV4cCI6MTY2NDU5NDA1M30.Km5MazbXWRtcaym1eagywG-r_3kcJ9PX_xGfZDkbLdE